language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

services:
  - redis-server

install:
  - pip install -r requirements.txt

script:
  - (cd test && python testrunner.py)
  - (cd src && make)

notifications:
  email:
    on_success: change
    on_failure: always
