language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"

services:
  - redis-server

install:
  - pip install -r test-requirements.txt
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - (flake8 --max-line-length=120 --max-complexity=8 --show-source --statistics src)
  - (cd src && py.test --genscript=blackred/test/testrunner.py -v && coverage run --source=blackred --omit="blackred/test/*" --branch blackred/test/testrunner.py)
  - (cd src && make)

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - (cd src && coverage report)
  - (cd src && coveralls)
