language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - redis-server

install:
  - pip install -U pip setuptools
  - pip install -r test-requirements.txt
  - pip install -r doc-requirements.txt
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - (cd src && make)

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - (cd src && coverage report)
  - (cd src && coveralls)
