language: python

python:
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy3"

services:
  - redis-server

install:
  - pip install coveralls
  - pip install docutils pygments
  - pip install -r requirements.txt

script:
  - (cd test && python testrunner.py)
  - (cd src && make)
  - (cd test && coverage run --source=../src/,../test/ --branch --omit="*setup.py*","*testrunner.py*" testrunner.py)

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - coveralls
