language: python

python:
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy3"

services:
  - redis-server

install:
  - pip install flake8
  - pip install coveralls
  - pip install docutils pygments
  - pip install -r requirements.txt

script:
  - (flake8 --max-line-length=120 --max-complexity=8 --show-source --statistics src test)
  - (cd src && make)
  - (cd test && coverage run --source=blackred --branch testrunner.py)

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - (cd test && coverage report)
  - (cd test && coveralls)
